### ISSUE TITLE
Eventlog object on Digital Marketing data with Event, Sequence ID and Transaction ID

### ISSUE THREAD

**Issue by heoa** [gertjanssenswillen/bupaR#12]
Digital Marketing data, such as Google Analytics data, can often be described in the format Event (productSKU), Sequence ID (the order of the purchase) and Transaction ID (such as session or buyer). Similar format is followed by tools such as SAS Visual Analytics [here](https://support.sas.com/resources/papers/proceedings17/0135-2017.pdf), page 3 with an example: in terms of SQL, this could be understood as `SELECT AGG(event) GROUP BY SeqID GROUP BY TransactID`. Sometimes, deeper clauses are useful as well.

BupaR [docs](https://www.bupar.net/materials/20170904%20poster%20bupaR.pdf) describes eventlog object with two helper functions, such as eventlog and simple_eventlog -- but I can not see easily how I would use them for digital marketing data.

**Is there any convenience functions to create eventlog object on Digital Marketing data with Event, SeqID and TransactionID?**

**Comment by gertjanssenswillen** [comment]
Thanks for your patience.

In Fig 3 (on page 3 of the SAS document), you have three variables: customer, call subject and date.

For this you could make an event log using simple_eventlog

`simple_eventlog(data, case_id = "customer", activity_id = "call subject", timestamp = "date")`

Data from equivalent context can be used in the same way, with the sole exception that the timestamp has to be a data/datetime variable, not just a numeric rank/order variable. You can find more information here: http://bupar.net/creating_eventlogs.html

Hope this helps!
