### ISSUE TITLE
How to user processmonitR dashboards outside of RStudio

### ISSUE THREAD

**Issue by riazarbi** [gertjanssenswillen/bupaR#15]
*Goal:* to use (any) processmontR dashboard standalone from RStudio. 

*Issue:* I can use any processmontiR dashboard function as part of an R scrip inside RStudio. When I run the function, a floating dashboard window pops up inside my RStudip Server browser window, and I can interact with it. But I can't figure out how to deploy the dashboard as a standalone shiny app, or to embed it into another shiny app.

*Request:* please indicate if running a processmontiR dashboard can run on a standalone shiny server, and if so, how.

*Further Information:* My environment is an RStudio server running in a docker container on my local machine. I access it at localhost:8787.

**Comment by gertjanssenswillen** [comment]
Thanks for your patience. 

Unfortunately, processmonitR currently only create gadgets, which cannot be deployed. See the following information from the Shiny documentation.

> 
> Where a Shiny app represents the output of an analysis, Shiny Gadgets are designed to be used in the course of analysis.
> 
> Where Shiny apps are designed to be used by end users, Shiny Gadgets are intended to be used by R users.
> 
> Where Shiny apps are ultimately intended to be deployed on servers (like Shiny Server or ShinyApps.io) and accessed via a web browser, Shiny Gadgets are only ever intended to be invoked from code (in the R console or from an R script) or from within RStudio.

In the future the package is intended to be extended and support also the creating of Shiny apps for process data, but the timing is unclear. Until then, what you can do in the meantime is copy the code from the functions (on github), and remove the outer ui-elements with proper shiny app elements and use them in your own apps. The server and core ui will need no changes. 

Hope this helps.
Best, Gert
