### ISSUE TITLE
Filtering cases based on event data

### ISSUE THREAD

**Issue by jgonzale** [gertjanssenswillen/bupaR#21]
Hi.

I have a healthcare event log that includes emergency room events and hospital events. I would like to filter those cases whose emergency room facility was X (a variable included in the emergency room admission event) or those cases whose hospital facility was Y (a variable included in the hospital admission event).

Is it possible to filter complete cases based on characteristics of the events or I require a preprocessing of the data before constructing the log?

Regards,

**Comment by gertjanssenswillen** [comment]
Hi Juan

If I am right, you like to filter cases in which a certain value occurs for one of the events, but not necessarily for the whole case, is that correct?

I can see two ways to do that. One is by just filtering the events with the required attribute, and using the case_id's of those event to filter the cases

eventlog %>%
    filter(emergency_room == "X") -> selection 

eventlog %>%
   filter_case(case_id %in% selection$case_id) 

A second more direct approach is to use grouping and any(). You can group the event log by case, and then for each case check whether the event attribute value occurs for any of the events.

eventlog %>%
  group_by_case() %>%
  filter(any(emergency_room == "X")) %>%
  ungroup_eventlog()

The second approach is more direct, but might be less performant if you have a high number of cases, as the grouping might require a lot of resources. 

Does this answer your question?

**Comment by jgonzale** [comment]
Hi Gert.

Thanks for your fast answer.

Yes. This answer my question completely!

I didn't find this kind of filtering in the '[Subsetting event data](https://www.bupar.net/subsetting.html)' page and wasn't able to figure out that the `any` verb is the key to capture this cases (which is actually detailed in '[Enriching event data](https://www.bupar.net/enriching.html#custom_enrichment)' page).

In any case, thank you very much for your help and for the development of bupaR. A nice piece of code!

Regards,
