### ISSUE TITLE
lifecycle_id not found in data.frame

### ISSUE THREAD

**Issue by drhudgins** [gertjanssenswillen/bupaR#22]
lifecycle_id not found in data.frame error is popping up after latest update.

Here's one example: 
library(bupaR) 
library(edeaR) 
library(eventdataR)
data(patients)
precedence_matrix(patients)

Error in check_attributes(eventlog, attributes$attribute_name, attributes$attribute_values) : 
  lifecycle_id not found in data.frame

**Comment by gertjanssenswillen** [comment]
Are you sure you are using the latest version of bupaR? (0.4.2, on cran).

The error is due to changes in dplyr (version 0.8.0 released on Feb 15th, but the 0.4.2 release of bupaR should solve this.

**Comment by drhudgins** [comment]
That fixed it. Thank you.
