### ISSUE TITLE
Event log start and end timestamp support

### ISSUE THREAD

**Issue by jphillips-bp3** [gertjanssenswillen/bupaR#27]
Hi,

I am just learning about process mining and R so bear with me. I have used Apromore to do some process mining and it allows you to generate an XES event log file from a CVS file, and map timestamps to a Start Timestamp and an End Timestamp. This allows me to see the duration of activities (events). However the bupar event log only accepts a single timestamp. 

Let me explain in more detail. I guess a single timestamp would allow you to see the duration between the start of `Activity A` and the start of `Activity B` which would give you the time it takes to carry out `Activity A`. This is fine if `Activity B` follows on immediately from `Activity A` with no delays.

However, in my situation, we have activities that have a start and end time, and the hand off from one activity to another might not be immediate. In this case, there is a time delay in the transition between the activities. Hopefully the diagram below makes what I am saying clearer:

<img width="1303" alt="Screenshot 2019-06-14 at 09 17 30" src="https://user-images.githubusercontent.com/4510278/59517013-79cc3c80-8eba-11e9-8e54-dd8a410bed1a.png">

In this diagram you can see that the `Hand Over Termination` activity takes on average 5.34 seconds, then the average time to hand off to the next activity in the process (`Termination Activity`) is 20.39 seconds. It is the ability to set a start and end timestamp for the events that makes this level of analysis possible (at least in my mind).

So my question is, is there a way of manipulating the event log to accept a start and end timestamp and be able to use the time difference to analyse the duration of the activities and transitions between them?

Many thanks

**Comment by gertjanssenswillen** [comment]
Hi Justin. 

I suppose your data is formatted so that multiple timestamps (start + complete) are stored as seperate variables next to each other? In that case you can use the activities_to_eventlog function (https://gertjanssenswillen.github.io/bupaR/reference/activities_to_eventlog.html), where you can supply the timestamp variables as a vector. 

If your data has another format, please describe it to me and I can help you to proceed.

**Comment by jphillips-bp3** [comment]
Hi @gertjanssenswillen thank you for the update. Indeed yes the start and complete timestamps are separate variables. I will give the function a try.
