### ISSUE TITLE
issue with sample_n

### ISSUE THREAD

**Issue by spedygiorgio** [gertjanssenswillen/bupaR#3]
Hi, thanks for your very useful package!
I am having an issue using sample_n function:
`sottinsiemesx <- evl_f %>% bupaR::sample_n(1000)
Error in UseMethod("case_id") : 
  no applicable method for 'case_id' applied to an object of class "function"`

evl_f  is an eventlog object.
Any suggestion?

**Comment by gertjanssenswillen** [comment]
This is a bug introduced in the latest version and has been solved today. Just reinstall the package from github using devtools::install_github("gertjanssenswillen/bupaR").

**Comment by spedygiorgio** [comment]
Thanks great
