### ISSUE TITLE
pmap issue in the eventlog function

### ISSUE THREAD

**Issue by tasilva96** [gertjanssenswillen/bupaR#6]
Hello there!

If I use the eventlog function I will get the following error (similar error was reported in Stackoverflow):
```
eventlog %>%
  eventlog(case_id = case_classifier,
    activity_id = "activity_id",
    activity_instance_id = "activity_instance_id",
    timestamp = "timestamp",
    lifecycle_id = "lifecycle_id",
    resource_id = "resource_id") -> eventlog

Error in .f(.l[[c(1L, i)]], .l[[c(2L, i)]], ...) : 
  ..2 used in an incorrect context, no ... to look in
```

I dig in the function. The error occurs here: 
```
 attribute_list <- pmap(list(args_values, args_names),
    ~list(attribute_name = ..2,
      attribute_values = ..1))
```
This code fix:
```
  attribute_list <- pmap(list(args_values, args_names),
    ~list(attribute_name = .y,
      attribute_values = .x))

```
When we have two arguments, it is recommend to use the .x and .y:
http://purrr.tidyverse.org/reference/map.html

I don't know why this fix the code. I have the most update version of purrr. 

Thank you!

**Comment by gertjanssenswillen** [comment]
Does it work using this version of bupaR (currently in another branch)?:

`devtools::install_github("gertjanssenswillen/bupaR", ref = "eventlog-ordering")`

**Comment by tasilva96** [comment]
Yes, this version fixed the problem!
Thank you!

Now, I have another issue to troubleshooting. 

```
my_test
Event log consisting of:
59173 events
Error in get(".order") : object '.order' not found
```
