### ISSUE TITLE
Error in set_global_graph_attrs(., attr = "rankdir", value = "LR", attr_type = "graph") :    could not find function "set_global_graph_attrs"

### ISSUE THREAD

**Issue by RuudPonthus** [gertjanssenswillen/bupaR#9]
Hi, 

I'm getting the following error when executing process_map:

> test_eventlog %>%
+     process_map(performance(median, "days"))
Error in set_global_graph_attrs(., attr = "rankdir", value = "LR", attr_type = "graph") : 
  could not find function "set_global_graph_attrs"

I'm running the latest version of DiagrammeR and bupaR

> traceback()
16: function_list[[i]](value)
15: freduce(value, `_function_list`)
14: `_fseq`(`_lhs`)
13: eval(quote(`_fseq`(`_lhs`)), env, env)
12: eval(quote(`_fseq`(`_lhs`)), env, env)
11: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
10: create_graph(nodes_df, edges_df) %>% set_global_graph_attrs(attr = "rankdir", 
        value = "LR", attr_type = "graph") %>% colorize_node_attrs(node_attr_from = "color_level", 
        node_attr_to = "fillcolor", palette = ifelse(perspective == 
            "performance", "Reds", "PuBu"), default_color = "white", 
        cut_points = seq(min_level - 0.1, max_level + 0.1, length.out = 9))
9: process_map(., performance(median, "days"))
8: function_list[[k]](value)
7: withVisible(function_list[[k]](value))
6: freduce(value, `_function_list`)
5: `_fseq`(`_lhs`)
4: eval(quote(`_fseq`(`_lhs`)), env, env)
3: eval(quote(`_fseq`(`_lhs`)), env, env)
2: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
1: test_eventlog %>% process_map(performance(median, "days"))

**Comment by geilerloui** [comment]
same problem need help ! thanks

**Comment by gertjanssenswillen** [comment]
Please check the answer here:
https://github.com/gertjanssenswillen/processmapR/issues/11
